<div class="container">
    <h1>Página Sobre Empresa</h1>
    <br><br>
    <p style="display: flex;">
        <img src="<?= URL; ?>assets/img/company.jpg" height="250" alt="Imagem da Empresa" style="margin-right:20px;">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.
    </p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga dicta nostrum expedita sint veritatis amet adipisci magni explicabo ratione, ducimus natus obcaecati tempore deleniti ipsum facilis voluptas, tenetur nam aperiam, optio accusamus corrupti. Fuga, aut cupiditate facere nisi exercitationem quo! Nobis impedit ea quia voluptas asperiores? Quis ut assumenda placeat, eos ipsam vero nesciunt amet recusandae architecto tenetur eligendi tempora aliquam porro distinctio adipisci ipsum quibusdam neque veritatis molestiae voluptatum repellat unde, doloremque quasi officiis. Quaerat tempore possimus saepe nisi veritatis repudiandae commodi odio dicta distinctio eveniet dolor non libero nihil nesciunt iusto ab aliquam, iste quos voluptates, dolore laboriosam.</p>
    <br><br>
</div>